### ISSUE TITLE
TTSFox stops at first sentence end of selected paragraph when rewinding with Shift-Click

### ISSUE THREAD

**Issue by pal1000** [ettoolong/TTSFox#21]
### Steps to reproduce
- Have TTSFox configured to use Speech Window;
- Pause before it is done reading;
- Select a paragraph or sentence to resume from and use Shift-Click to resume reading from the start of selected paragraph or sentence.
### Result
TTSFox will stop at the end of the selected sentence. If I use Click then resume button to rewind it works as expected,  It doesn't stop until it reaches the end of the text area.

**Comment by ettoolong** [comment]
According last update:
> shift + click on sentence to read out it ( cursor would keep on original position ).

If you need move cursor, you should: (before 0.0.25)
1. click on sentence (that will move cursor to start of sentence)
2. click resume button

In version 0.0.25 update, you can:
1. click on sentence (that will move cursor to start of sentence)
2. click on the SAME sentence again (that will trigger resume)

**Comment by pal1000** [comment]
Thanks for implementing double click shortcut for rewind and resume to end. Didn't know Shift-Click was actually intended to work as rewind and read a single sentence only. Anyway my concern is satisfied so I close this.
