### ISSUE TITLE
 browser.windows.create() doesn't paint popup

### ISSUE THREAD

**Issue by bunnybooboo** [ettoolong/TTSFox#3]
Flagging for your attention. Behaviour seen in 57 (Beta 57.0b4) and 58 (Nightly build id 20170930100302). Bug already submitted so shared specifics from this WebExtension to assist their further investigation. https://bugzilla.mozilla.org/show_bug.cgi?id=1402110#c3

**Comment by pal1000** [comment]
Workaround:

```

document.addEventListener("DOMContentLoaded", (event) => {
    // Fix for Fx57 bug where bundled page loaded using
    // browser.windows.create won't show contents unless resized.
    // See https://bugzilla.mozilla.org/show_bug.cgi?id=1402110
    browser.windows.getCurrent((win) => {
        browser.windows.update(win.id, {width:win.width+1})
    })
});

```

**Comment by ettoolong** [comment]
Add workaround in version 0.0.15.

**Comment by pal1000** [comment]
@bunnybooboo please re-test this with 0.0.16.

**Comment by bunnybooboo** [comment]
Firefox Nightly (58)
Build ID: 20171111220358
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0
OS: Linux 4.13.11-1-ARCH

- Bug reproducing

Firefox Beta (57)
Build ID: 20171109183137
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0
OS: Linux 4.13.11-1-ARCH

-  Bug reproducing

**Comment by bunnybooboo** [comment]
Firefox Release (56)
Build ID: 20171024165158
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0
OS: Linux 4.13.11-1-ARCH

- Bug NOT reproducing

**Comment by bunnybooboo** [comment]
Observed fix in that other repo https://github.com/aecreations/clippings/commit/746b7b825513a5fe147103767577eb28de66dcc3

**Comment by bunnybooboo** [comment]
Yay!! Fixed!! Thanks for your efforts.
