### ISSUE TITLE
TTSFox doesn't stop when closing web page with TTS reading in progress

### ISSUE THREAD

**Issue by pal1000** [ettoolong/TTSFox#5]
It only affects `Speech selected text` mode. It doesn't affect speech window.
It doesn't matter how you close the web page with TTS reading in progress:
- close the tab;
- browse to other web page on same tab;
- close the window containing the aforementioned tab as long as there is at least one Firefox window that remained open,

Video: (dead link).

**Comment by ettoolong** [comment]
Fixed in version 0.0.14

Thanks.
