### ISSUE TITLE
Voice selection element awkward positioning

### ISSUE THREAD

**Issue by pal1000** [ettoolong/TTSFox#6]
Video: (dead link)

I don't think there is a problem if voice selection element expands on top of other settings such as speed and pitch as long as it compacts itself back on click away. I think a regular HTML select element should work just fine.

**Comment by ettoolong** [comment]
I can't reproduce this bug. (test on  MacOS 10.12 & Win10)

In version 0.0.14, I modify some preference page style.
You can test this issue again and tell me the result. Thanks.

**Comment by pal1000** [comment]
I think it has to do with screen resolution.  I think you can only reproduce it if screen resolution is low enough, e.g. 1024x768. Anyway, the changes you made improved the situation enough to close this. When voice selector is expanded the selected TTS engine appears in the bottom-most part of the add-on configuration page and is visible in full now without zoom-out. I can simply press up or down and select the one I want.

**Comment by ettoolong** [comment]
I can reproduce this bug now.
This bug only on Firefox windows, not on Mac.
Any add-on with HTML default select element in option UI can reproduce this bug.
e.g.: HTML5 Video everywhere / LanguageTool Grammar Checker. 
If you scroll page in option UI, the dropdown menu will appears on the wrong position.
Maximize / restore window can fix it temporarily, if you scroll page, it broken again.

**Comment by pal1000** [comment]
I tested Firefox 58 beta 4 developer edition until NoScript 10 was released on November 21 and couldn't reproduce this on that environment, so i think it is a Firefox 57 and older on Windows only glitch.
Another glitch I noticed is when Firefox window is maximized it gets restored to normal window when opening TTTSFox Options either via double click or clicking on Options in Add-Ons Manager.

**Comment by pal1000** [comment]
Latest version 0.0.21 restored this bug in full so I have to re-open. The un-maximize glitch reported in my previous comment is gone.

I think the best course of action is to move TTSFox options from Add-Ons Manager to the moz-extension speech window and have the Options button from Add-Ons manager open the speech window.

I saw this approach used by most webextensions.

Screenshot:
![ttsfox-lang-select-glitch](https://user-images.githubusercontent.com/1138235/33336445-9c5232a8-d478-11e7-8bf5-003c5fb6cedc.png)

**Comment by ettoolong** [comment]
I can add a button on option page to allow user open option_ui in new tab, then wait Firefox fix it.

see:
https://bugzilla.mozilla.org/show_bug.cgi?id=1387627
https://bugzilla.mozilla.org/show_bug.cgi?id=1406948
https://bugzilla.mozilla.org/show_bug.cgi?id=1381321

**Comment by pal1000** [comment]
Yes, that's what I suggested above.

**Comment by pal1000** [comment]
Fixed in full in 0.0.22 so I close this.
