### ISSUE TITLE
Auto start speech when speech window opened only works once

### ISSUE THREAD

**Issue by pal1000** [ettoolong/TTSFox#7]
When using `Speech window` mode and `Auto start speech when speech window opened` is enabled, auto start speaking only works once.  You have to close the speech window to make it auto-read again.

### Steps to replicate:
- Visit a website with a lot of text, e.g. a news website and pick an article.
- Having TTSFox configured in the aforementioned manner select a small chunk of text and have TTSFox read it.
- While it's reading minimize the speech window then wait for it to finish. This way TTSFox speech window remains open for subsequent speech tasks.
- Select another chunk of text and have TTSFox read it as well.

### What happens:
- TTSFox updates the content of speech window.

### What should happen:
- TTSFox updates the content of speech window.
- TTSFox reads the new content.

As an extra when this bug is fixed `Auto start speech when speech window opened` should be renamed to `Auto start speaking when using speech window`.

**Comment by ettoolong** [comment]
Fixed in version 0.0.14

Thanks.
